# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The Commons Platform
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  The Commons Platform is an open source social media platform, decentralised governance framework 
  and economic ecosystem. It is designed to respect users and assist in the stewardship of the commons, 
  looking after resources that belong to everyone. Whether you come from a cultural, religious, 
  geographic or sexual minority, regardless of disability, be you an activist, a persecuted member of 
  society, or just someone fed up with the current status quo, you can find a home with the Commons 
  Platform. Together, we can pool our talent and resources to build a brighter world for everyone.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
